### PR TITLE
Ruby VFX

### PR DESCRIPTION
**Pull request by s220452**
Snowstorm, ice spikes and explosion are complete, rest are WIP

### CODE REVIEW

**Review by Tom-J991 — CHANGES_REQUESTED** [review]
There are changes in the quality settings file that have been committed, preferable if that wasn't committed unless there's a good reason for it.

**Comment by s220452** [comment]
As far as I'm aware the only change is the Render Pipeline Asset is set to URP_Asset which is required for the VFX to render.

**Comment by Tom-J991** [comment]
> As far as I'm aware the only change is the Render Pipeline Asset is set to URP_Asset which is required for the VFX to render.

It has already been set to that in the main branch, I'd just say to remove the quality settings file from the commit anyways to avoid any potential issues with the different reference ids, if there are any issues later then we can resolve it then.
Have you updated your branch from main recently? Could've happened if your branch has outdated settings.

**Comment by s220452** [comment]
I fetched the latest main and merged it into my branch just before creating the pull request. I will remove the quality settings file from the pull request if the changes needed have already been made in main. Not sure where the difference is coming from

**Review by Tom-J991 — APPROVED** [review]

**Pull request merged**
